---

- name: Helm Rancher repository
  kubernetes.core.helm_repository:
    name: rancher-latest
    repo_url: "https://releases.rancher.com/server-charts/latest"
  when: 'ansible_hostname | string in rke2_master_node'

- name: Helm Rancher repository
  kubernetes.core.helm_repository:
    name: jetstack
    repo_url: "https://charts.jetstack.io"
  when: 'ansible_hostname | string in rke2_master_node'

- name: Deploy latest version of Cert Manager
  kubernetes.core.helm:
    name: cert-manager
    chart_ref: jetstack/cert-manager
    release_namespace: cert-manager
    create_namespace: true
    values:
      crds:
        enabled: true
  when: 'ansible_hostname | string in rke2_master_node'

- name: Setting Rancher admin password
  ansible.builtin.set_fact:
    rancher_admin_passwd: "{{ lookup('community.hashi_vault.vault_kv2_get', 'RKE2/cluster/{{ rke2_cluster_name }}/rancher', engine_mount_point='secret') }}"
  when: 'ansible_hostname | string in rke2_master_node'

- name: Deploy latest version of Rancher Manager
  kubernetes.core.helm:
    name: rancher
    chart_ref: rancher-latest/rancher
    chart_version: '{{ rancher_chart_version }}'
    release_namespace: cattle-system
    create_namespace: true
    values:
      hostname: '{{ rancher_hostname }}'
      replicas: 3
      bootstrapPassword: '{{ rancher_admin_passwd.secret.password }}'
      proxy: '{{ proxy_url }}'
      noProxy: '{{ no_proxy }}'
  when: 'ansible_hostname | string in rke2_master_node'
